apiVersion: apps/v1
kind: Deployment
metadata:
  name: maia-jouenne-mlops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maia-jouenne-mlops-app
  template:
    metadata:
      labels:
        app: maia-jouenne-mlops-app
    spec:
      containers:
      - name: maia-jouenne-mlops-app
        image: maia-jouenne-mlops-app:v1  
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: maia-jouenne-mlops-service
spec:
  type: LoadBalancer
  ports:
  - port: 8501
    targetPort: 8501
  selector:
    app: maia-jouenne-mlops-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: maia-jouenne-mlops-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: maia-jouenne-mlops-service
            port:
              number: 8501
